export const aiProjects = [
  {
    id: "echo",
    name: "ECHO",
    tagline: "Autonomous meeting autopilot",
    description:
      "Five specialist agents coordinate after every Zoom/Meet/Teams call — extracting action items, updating CRM, drafting follow-up emails, and creating tasks. By the time you leave the meeting, the work is done.",
    tags: ["Multi-agent", "Recall.ai", "TypeScript", "LLM orchestration"],
    badge: "Milan AI Week 2026",
    badgeType: "accent" as const,
    github: "https://github.com/thisisaman408/echo",
    live: null,
    featured: true,
  },
  {
    id: "renatus",
    name: "Renatus",
    tagline: "Audit-grade code migration engine",
    description:
      "Four agents share one engine: Migrate, Refactor, Security Audit, and Codebase Q&A. Every LLM-driven change is sandboxed, executed, and shipped with a cryptographically signed audit report.",
    tags: ["LLM agents", "TypeScript", "Sandbox execution", "Audit chain"],
    badge: "IBM Bob Hackathon",
    badgeType: "accent" as const,
    github: "https://github.com/thisisaman408/renatus",
    live: "https://renatus-iota.vercel.app",
    featured: true,
  },
  {
    id: "tower",
    name: "Tower",
    tagline: "Gemini Vision competitor intelligence",
    description:
      "Drop competitors on a watchlist. Tower scrapes pricing, careers, and blog pages daily. Gemini Vision reads the actual screenshots. A diff engine catches week-over-week changes and fires a board-ready memo to Slack.",
    tags: ["Gemini Vision", "TypeScript", "Web scraping", "Slack"],
    badge: null,
    badgeType: null,
    github: "https://github.com/thisisaman408/tower-app",
    live: "https://tower-app-peach.vercel.app",
    featured: true,
  },
  {
    id: "outmate",
    name: "Outmate.AI",
    tagline: "B2B data intelligence + outreach automation",
    description:
      "Aggregates leads from Crustdata, Explorium, and ContactOut. AI agents research each prospect and trigger personalized outreach sequences automatically.",
    tags: ["Python", "Multi-provider", "AI agents", "B2B"],
    badge: null,
    badgeType: null,
    github: "https://github.com/thisisaman408/outmate-agentic-infra",
    live: "https://outmate-agentic-infra.vercel.app",
    featured: false,
  },
  {
    id: "lia",
    name: "Lia Plus",
    tagline: "Hybrid NLP AI assistant",
    description:
      "Hybrid engine combining VADER rule-based heuristics with dynamic LLM context adjustments. FastAPI backend, real-time sentiment analysis, multi-turn conversation management.",
    tags: ["FastAPI", "Python", "NLP", "VADER", "JavaScript"],
    badge: null,
    badgeType: null,
    github: "https://github.com/thisisaman408/Lia",
    live: "https://liafrontend-five.vercel.app",
    featured: false,
  },
  {
    id: "mirofish",
    name: "Mirofish MCP Server",
    tagline: "MCP server for multi-agent prediction",
    description:
      "Connect Claude Code (or any MCP client) directly to MiroFish — an AI-powered engine that builds knowledge graphs, spins up thousands of autonomous agents, and simulates future scenarios.",
    tags: ["MCP", "JavaScript", "Knowledge graph", "AI agents"],
    badge: null,
    badgeType: null,
    github: "https://github.com/thisisaman408/mirofish-mcp-server",
    live: null,
    featured: false,
  },
];

export const freelanceProjects = [
  {
    id: "shoehub",
    name: "Shoe Hub 83",
    tagline: "Authentic sneaker resell",
    description: "Full e-commerce site for Himanshu's sneaker brand — 38.5K Instagram followers, Delhi.",
    tags: ["E-commerce", "Next.js", "TypeScript"],
    live: "https://am-shoe-hub-83.vercel.app",
    github: "https://github.com/thisisaman408/am-shoe-hub-83",
    category: "E-commerce",
  },
  {
    id: "stonewood",
    name: "Stonewood Architects",
    tagline: "Architecture & interiors studio",
    description: "Digital presence for a Gurugram architecture firm established in 2003. Turnkey builds and interior design.",
    tags: ["Architecture", "Next.js", "TypeScript"],
    live: null,
    github: "https://github.com/thisisaman408/am-stonewood-architects",
    category: "Architecture",
  },
  {
    id: "saloni",
    name: "Saloni Saloon",
    tagline: "Premium salon experience",
    description: "Modern booking and brand website for a premium salon.",
    tags: ["Beauty", "Next.js", "TypeScript"],
    live: "https://saloni-saloon.vercel.app",
    github: "https://github.com/thisisaman408/Saloni-Saloon",
    category: "Beauty",
  },
  {
    id: "brass",
    name: "Moradabad Brass Atelier",
    tagline: "Hand-finished brass exports",
    description: "Export-grade product catalogue for an EPCH-listed brass manufacturer, established 1991.",
    tags: ["Export", "Next.js", "Product"],
    live: null,
    github: "https://github.com/thisisaman408/am-moradabad-brass-exports",
    category: "Manufacturing",
  },
  {
    id: "sarees",
    name: "Karol Bagh Designer Sarees",
    tagline: "Banarasi · Kanjivaram · bridal",
    description: "Online presence for a heritage saree boutique in Delhi's Karol Bagh, est. 2008.",
    tags: ["Fashion", "Next.js", "E-commerce"],
    live: null,
    github: "https://github.com/thisisaman408/am-karol-bagh-designer-sarees",
    category: "Fashion",
  },
  {
    id: "handicrafts",
    name: "Anushka Handicrafts",
    tagline: "Jaipur marble, wood & metal",
    description: "Artisan handicraft house from Jaipur — marble, wood, metal, and textile exports, est. 2015.",
    tags: ["Handicrafts", "Next.js", "Export"],
    live: null,
    github: "https://github.com/thisisaman408/am-anushka-handicrafts",
    category: "Artisan",
  },
  {
    id: "ramsha",
    name: "Ramsha Arts",
    tagline: "Saharanpur sheesham wood",
    description: "Tableware and home decor brand using mango and sheesham wood from Saharanpur, est. 1986.",
    tags: ["Wood craft", "Next.js", "Export"],
    live: null,
    github: "https://github.com/thisisaman408/am-ramsha-arts",
    category: "Artisan",
  },
  {
    id: "swan",
    name: "Swan Garments",
    tagline: "Fashion & apparel",
    description: "Brand website and online catalogue for Swan Garments.",
    tags: ["Fashion", "Next.js", "TypeScript"],
    live: "https://swan-garments.vercel.app",
    github: "https://github.com/thisisaman408/Swan-Garments",
    category: "Fashion",
  },
  {
    id: "fitnes",
    name: "Fitnes Gym",
    tagline: "Rohini & Saket Select City Walk",
    description: "Gym chain website covering two Delhi locations — Rohini and Saket Select City Walk.",
    tags: ["Fitness", "Next.js", "TypeScript"],
    live: "https://fitnes-gym-rohini.vercel.app",
    github: "https://github.com/thisisaman408/fitnes-gym-rohini",
    category: "Fitness",
  },
  {
    id: "bhawani",
    name: "Bhawani",
    tagline: "Business web presence",
    description: "Full web presence and digital branding for a local business.",
    tags: ["Business", "Next.js", "TypeScript"],
    live: "https://bhawani-virid.vercel.app",
    github: "https://github.com/thisisaman408/bhawani",
    category: "Business",
  },
];

export const otherProjects = [
  {
    name: "AmanGram",
    tagline: "Social media platform",
    description: "Full-stack Instagram-like social media. Real-time feed, follow system, media uploads.",
    tags: ["TypeScript", "Next.js", "Social"],
    live: "https://amangram.vercel.app",
    github: "https://github.com/thisisaman408/SocialMedia",
  },
  {
    name: "SEOHUB",
    tagline: "SEO analytics tool",
    description: "Full-stack SEO analysis and reporting platform. Express backend + React frontend.",
    tags: ["TypeScript", "Express", "SEO"],
    live: "https://seohub-frontend-omega.vercel.app",
    github: "https://github.com/thisisaman408/SEOHUB_FRONTEND",
  },
  {
    name: "MoveFlix",
    tagline: "Movie streaming platform",
    description: "Movie discovery and streaming UI with search, genres, and watchlists.",
    tags: ["JavaScript", "API", "Movies"],
    live: "https://move-flix.vercel.app",
    github: "https://github.com/thisisaman408/MoveFlix",
  },
  {
    name: "FEST",
    tagline: "College festival management",
    description: "End-to-end festival management system with event registration, participant tracking, and admin dashboard.",
    tags: ["Python", "FastAPI", "React"],
    live: "https://fest-front-t5ix.vercel.app",
    github: "https://github.com/thisisaman408/FEST_FRONT",
  },
  {
    name: "AQI Predictor",
    tagline: "Air quality ML model",
    description: "Machine learning model predicting Air Quality Index using environmental sensor data.",
    tags: ["Python", "ML", "Data science"],
    live: null,
    github: "https://github.com/thisisaman408/AQIPredictor",
  },
  {
    name: "Pair Trading",
    tagline: "Quantitative finance strategy",
    description: "Statistical arbitrage pair-trading engine with cointegration analysis and backtesting.",
    tags: ["Python", "Finance", "Quant"],
    live: null,
    github: "https://github.com/thisisaman408/Pair-Trading",
  },
];

export const skills = {
  "AI / Agents": ["LLM orchestration", "Multi-agent systems", "MCP servers", "RAG pipelines", "FastAPI", "LangChain"],
  "Frontend": ["Next.js", "React", "TypeScript", "Tailwind CSS", "Framer Motion"],
  "Backend": ["Node.js", "Python", "Express", "FastAPI", "REST APIs"],
  "Data / ML": ["Python ML", "scikit-learn", "pandas", "R", "Statistical analysis"],
  "Tools": ["Git", "Vercel", "Supabase", "PostgreSQL", "Firebase", "Docker"],
  "Creative": ["Brand video production", "Marketing strategy", "UI/UX design", "Motion graphics"],
};

export const stats = [
  { value: "10+", label: "freelance clients" },
  { value: "3", label: "AI hackathons" },
  { value: "75+", label: "GitHub repos" },
  { value: "∞", label: "projects shipped" },
];
