export const socials = {
  github: "https://github.com/thisisaman408",
  email: "mailto:thisisaman408@gmail.com",
  x: "https://x.com/maiiamanhu",
  linkedin: "https://www.linkedin.com/in/thisisaman408/",
  discord: "https://discord.gg/8AJuJRP2",
};

export const aiProjects = [
  {
    id: "resyl",
    name: "Resyl",
    tagline: "AI-powered brand creation platform",
    description:
      "Founded Resyl — an AI platform that helps founders and marketers build brand identities, generate marketing assets, and produce brand videos using Claude and generative AI. From logo to launch video, in minutes.",
    tags: ["Founder", "Next.js", "Claude AI", "Brand creation", "TypeScript"],
    badge: "Founder",
    badgeType: "purple" as const,
    github: null,
    live: "https://resyl.app",
    screenshot: "/screenshots/resyl.jpg",
    color: "#A78BFA",
    featured: true,
  },
  {
    id: "echo",
    name: "ECHO",
    tagline: "Autonomous meeting autopilot",
    description:
      "Five specialist agents coordinate after every Zoom/Meet/Teams call — extracting action items, updating CRM, drafting follow-up emails, and creating tasks. By the time you leave the meeting, the work is done.",
    tags: ["Multi-agent", "Recall.ai", "TypeScript", "LLM orchestration"],
    badge: "Milan AI Week 2026",
    badgeType: "accent" as const,
    github: "https://github.com/thisisaman408/echo",
    live: null,
    screenshot: "/screenshots/echo.jpg",
    color: "#C8FF00",
    featured: true,
  },
  {
    id: "renatus",
    name: "Renatus",
    tagline: "Audit-grade code migration engine",
    description:
      "Four agents share one engine: Migrate, Refactor, Security Audit, and Codebase Q&A. Every LLM-driven change is sandboxed, executed, and shipped with a cryptographically signed audit report.",
    tags: ["LLM agents", "TypeScript", "Sandbox execution", "Audit chain"],
    badge: "IBM Bob Hackathon",
    badgeType: "accent" as const,
    github: "https://github.com/thisisaman408/renatus",
    live: "https://renatus-iota.vercel.app",
    screenshot: "/screenshots/renatus.jpg",
    color: "#38BDF8",
    featured: true,
  },
  {
    id: "tower",
    name: "Tower",
    tagline: "Gemini Vision competitor intelligence",
    description:
      "Drop competitors on a watchlist. Tower scrapes pricing, careers, and blog pages daily. Gemini Vision reads the actual screenshots. A diff engine catches week-over-week changes and fires a board-ready memo to Slack.",
    tags: ["Gemini Vision", "TypeScript", "Web scraping", "Slack"],
    badge: null,
    badgeType: null,
    github: "https://github.com/thisisaman408/tower-app",
    live: "https://tower-app-peach.vercel.app",
    screenshot: "/screenshots/tower.jpg",
    color: "#FB923C",
    featured: false,
  },
  {
    id: "outmate",
    name: "Outmate.AI",
    tagline: "B2B data intelligence + outreach automation",
    description:
      "Aggregates leads from Crustdata, Explorium, and ContactOut. AI agents research each prospect and trigger personalized outreach sequences automatically.",
    tags: ["Python", "Multi-provider", "AI agents", "B2B"],
    badge: null,
    badgeType: null,
    github: "https://github.com/thisisaman408/outmate-agentic-infra",
    live: "https://app.outmate.ai",
    screenshot: "/screenshots/outmate.jpg",
    color: "#F472B6",
    featured: false,
  },
  {
    id: "lia",
    name: "Lia Plus",
    tagline: "Hybrid NLP AI assistant",
    description:
      "Hybrid engine combining VADER rule-based heuristics with dynamic LLM context adjustments. FastAPI backend, real-time sentiment analysis, multi-turn conversation management.",
    tags: ["FastAPI", "Python", "NLP", "VADER"],
    badge: null,
    badgeType: null,
    github: "https://github.com/thisisaman408/Lia",
    live: "https://liafrontend-five.vercel.app",
    screenshot: "/screenshots/lia.jpg",
    color: "#4ADE80",
    featured: false,
  },
  {
    id: "mirofish",
    name: "Mirofish MCP Server",
    tagline: "MCP server for multi-agent prediction",
    description:
      "Connect Claude Code (or any MCP client) directly to MiroFish — an AI-powered engine that builds knowledge graphs, spins up thousands of autonomous agents, and simulates future scenarios.",
    tags: ["MCP", "JavaScript", "Knowledge graph"],
    badge: null,
    badgeType: null,
    github: "https://github.com/thisisaman408/mirofish-mcp-server",
    live: null,
    screenshot: null,
    color: "#C084FC",
    featured: false,
  },
];

export const freelanceProjects = [
  {
    id: "shoehub",
    name: "Shoe Hub 83",
    tagline: "Authentic sneaker resell",
    description: "Full e-commerce site for Himanshu's sneaker brand — 38.5K Instagram followers, Delhi.",
    tags: ["E-commerce", "Next.js"],
    live: "https://am-shoe-hub-83.vercel.app",
    github: "https://github.com/thisisaman408/am-shoe-hub-83",
    screenshot: "/screenshots/shoehub.jpg",
    category: "E-commerce",
    color: "#FF6B6B",
  },
  {
    id: "stonewood",
    name: "Stonewood Architects",
    tagline: "Architecture & interiors",
    description: "Digital presence for a Gurugram architecture firm, est. 2003.",
    tags: ["Architecture", "Next.js"],
    live: null,
    github: "https://github.com/thisisaman408/am-stonewood-architects",
    screenshot: "/screenshots/stonewood.jpg",
    category: "Architecture",
    color: "#94A3B8",
  },
  {
    id: "saloni",
    name: "Saloni Saloon",
    tagline: "Premium salon brand",
    description: "Modern booking and brand site for a premium Delhi salon.",
    tags: ["Beauty", "Next.js"],
    live: "https://saloni-saloon.vercel.app",
    github: "https://github.com/thisisaman408/Saloni-Saloon",
    screenshot: "/screenshots/saloni.jpg",
    category: "Beauty",
    color: "#F9A8D4",
  },
  {
    id: "brass",
    name: "Moradabad Brass Atelier",
    tagline: "Hand-finished brass exports",
    description: "EPCH-listed brass manufacturer, est. 1991.",
    tags: ["Export", "Next.js"],
    live: null,
    github: "https://github.com/thisisaman408/am-moradabad-brass-exports",
    screenshot: "/screenshots/brass.jpg",
    category: "Manufacturing",
    color: "#FCD34D",
  },
  {
    id: "sarees",
    name: "Karol Bagh Sarees",
    tagline: "Banarasi · Kanjivaram · bridal",
    description: "Heritage saree boutique, Karol Bagh Delhi, est. 2008.",
    tags: ["Fashion", "Next.js"],
    live: null,
    github: "https://github.com/thisisaman408/am-karol-bagh-designer-sarees",
    screenshot: "/screenshots/sarees.jpg",
    category: "Fashion",
    color: "#F472B6",
  },
  {
    id: "handicrafts",
    name: "Anushka Handicrafts",
    tagline: "Jaipur marble, wood & metal",
    description: "Artisan house from Jaipur, est. 2015.",
    tags: ["Handicrafts", "Next.js"],
    live: null,
    github: "https://github.com/thisisaman408/am-anushka-handicrafts",
    screenshot: "/screenshots/anushka.jpg",
    category: "Artisan",
    color: "#86EFAC",
  },
  {
    id: "ramsha",
    name: "Ramsha Arts",
    tagline: "Saharanpur sheesham wood",
    description: "Tableware and home decor from mango & sheesham wood, est. 1986.",
    tags: ["Wood craft", "Next.js"],
    live: null,
    github: "https://github.com/thisisaman408/am-ramsha-arts",
    screenshot: "/screenshots/ramsha.jpg",
    category: "Artisan",
    color: "#A3E635",
  },
  {
    id: "bhawani",
    name: "Bhawani",
    tagline: "Brand & web presence",
    description: "Custom web presence built for a client — clean, modern, conversion-focused.",
    tags: ["Client site", "Next.js"],
    live: "https://bhawani-virid.vercel.app",
    github: "https://github.com/thisisaman408/bhawani",
    screenshot: "/screenshots/bhawani.jpg",
    category: "Business",
    color: "#F97316",
  },
  {
    id: "fitnes-saket",
    name: "Fit Saket Gym",
    tagline: "Select City Walk, Delhi",
    description: "Second gym site for the Fitnes chain — premium location at Saket Select City Walk, South Delhi.",
    tags: ["Fitness", "Next.js"],
    live: "https://fitness-fit-saket-select-city-walk.vercel.app",
    github: "https://github.com/thisisaman408/fitness-fit-saket-select-city-walk-gym",
    screenshot: "/screenshots/fitnes-saket.jpg",
    category: "Fitness",
    color: "#34D399",
  },
  {
    id: "swan",
    name: "Swan Garments",
    tagline: "Fashion & apparel",
    description: "Brand website and online catalogue.",
    tags: ["Fashion", "Next.js"],
    live: "https://swan-garments.vercel.app",
    github: "https://github.com/thisisaman408/Swan-Garments",
    screenshot: "/screenshots/swan.jpg",
    category: "Fashion",
    color: "#67E8F9",
  },
  {
    id: "fitnes",
    name: "Fitnes Gym",
    tagline: "Rohini & Saket Delhi",
    description: "Gym chain website — two Delhi locations.",
    tags: ["Fitness", "Next.js"],
    live: "https://fitnes-gym-rohini.vercel.app",
    github: "https://github.com/thisisaman408/fitnes-gym-rohini",
    screenshot: "/screenshots/fitnes.jpg",
    category: "Fitness",
    color: "#4ADE80",
  },
];

export const otherProjects = [
  {
    name: "AmanGram",
    tagline: "Social media platform",
    description: "Full-stack Instagram-like social media. Real-time feed, follow system, media uploads.",
    tags: ["TypeScript", "Next.js", "Social"],
    live: "https://amangram.vercel.app",
    github: "https://github.com/thisisaman408/SocialMedia",
    screenshot: "/screenshots/amangram.jpg",
    color: "#F472B6",
  },
  {
    name: "SEOHUB",
    tagline: "SEO analytics tool",
    description: "Full-stack SEO analysis and reporting platform.",
    tags: ["TypeScript", "Express", "SEO"],
    live: "https://seohub-frontend-omega.vercel.app",
    github: "https://github.com/thisisaman408/SEOHUB_FRONTEND",
    screenshot: "/screenshots/seohub.jpg",
    color: "#38BDF8",
  },
  {
    name: "MoveFlix",
    tagline: "Movie streaming platform",
    description: "Movie discovery and streaming UI with search, genres, and watchlists.",
    tags: ["JavaScript", "API", "Movies"],
    live: "https://move-flix.vercel.app",
    github: "https://github.com/thisisaman408/MoveFlix",
    screenshot: "/screenshots/moveflix.jpg",
    color: "#FB923C",
  },
  {
    name: "FEST",
    tagline: "College festival management",
    description: "End-to-end festival management system with event registration, participant tracking, and admin dashboard.",
    tags: ["Python", "FastAPI", "React"],
    live: "https://fest-front-t5ix.vercel.app",
    github: "https://github.com/thisisaman408/FEST_FRONT",
    screenshot: null,
    color: "#A78BFA",
  },
  {
    name: "AQI Predictor",
    tagline: "Air quality ML model",
    description: "Machine learning model predicting Air Quality Index using environmental sensor data.",
    tags: ["Python", "ML", "Data science"],
    live: null,
    github: "https://github.com/thisisaman408/AQIPredictor",
    screenshot: null,
    color: "#4ADE80",
  },
  {
    name: "Pair Trading",
    tagline: "Quantitative finance strategy",
    description: "Statistical arbitrage pair-trading engine with cointegration analysis and backtesting.",
    tags: ["Python", "Finance", "Quant"],
    live: null,
    github: "https://github.com/thisisaman408/Pair-Trading",
    screenshot: null,
    color: "#FCD34D",
  },
  {
    name: "GamingWebFrontEnd",
    tagline: "Cinematic gaming platform",
    description: "High-fidelity gaming platform UI — cinematic hero sections, character art, and a full metagame layer. React + Vite, zero-compromise design.",
    tags: ["React", "Vite", "UI/UX"],
    live: "https://gaming-web-front-end.vercel.app",
    github: "https://github.com/thisisaman408/GamingWebFrontEnd",
    screenshot: "/screenshots/gaming.jpg",
    color: "#818CF8",
  },
  {
    name: "Invoice Tool · C4GT",
    tagline: "Code for GovTech India",
    description: "Invoice management tool built for Code4GovTech — India's open-source government tech initiative. Ionic + Firebase.",
    tags: ["Ionic", "Firebase", "GovTech"],
    live: "https://invoice-new-tau.vercel.app",
    github: "https://github.com/thisisaman408/invoice-c4gt-firebase",
    screenshot: "/screenshots/invoice.jpg",
    color: "#F59E0B",
  },
];

export const skills = {
  "AI / Agents": { color: "#C8FF00", items: ["LLM orchestration", "Multi-agent systems", "MCP servers", "RAG pipelines", "Prompt engineering", "Claude API"] },
  "Brand & Creative": { color: "#F472B6", items: ["Brand video production", "Brand identity", "Marketing strategy", "Motion graphics", "UI/UX design"] },
  "Frontend": { color: "#38BDF8", items: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Framer Motion"] },
  "Backend": { color: "#FB923C", items: ["Node.js", "Python", "Express", "FastAPI", "REST APIs"] },
  "Data / ML": { color: "#4ADE80", items: ["scikit-learn", "pandas", "NumPy", "R", "Statistical analysis"] },
  "Tools": { color: "#A78BFA", items: ["Git", "Vercel", "Supabase", "PostgreSQL", "Firebase", "Docker"] },
};

export const stats = [
  { value: "10+", label: "businesses taken online" },
  { value: "3", label: "AI hackathons" },
  { value: "75+", label: "GitHub repos" },
  { value: "Always", label: "learning something new" },
];
